/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mSIbssVRYQu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Checkbox } from "@/components/ui/checkbox"

export default function classmanagement() {
  const [activeTab, setActiveTab] = useState("classes")
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <header className="sticky top-0 z-40 border-b bg-background px-4 py-3 shadow-sm sm:px-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link href="#" className="flex items-center gap-2 text-lg font-semibold" prefetch={false}>
              <BookIcon className="h-6 w-6" />
              <span>Faculty Dashboard</span>
            </Link>
          </div>
          <div className="flex items-center gap-4">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon" className="rounded-full">
                  <img
                    src="/placeholder.svg"
                    width={32}
                    height={32}
                    className="rounded-full"
                    alt="Avatar"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }}
                  />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>Logged in as John Doe</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Settings</DropdownMenuItem>
                <DropdownMenuItem>Sign out</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </header>
      <main className="flex-1 px-4 py-6 sm:px-6">
        <div className="grid gap-6">
          <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
            <TabsList className="flex w-full justify-start gap-4 border-b">
              <TabsTrigger value="classes">Your Classes</TabsTrigger>
              <TabsTrigger value="attendance">Attendance</TabsTrigger>
              <TabsTrigger value="grades">Grades</TabsTrigger>
            </TabsList>
            <TabsContent value="classes">
              <div className="grid gap-4">
                <div className="flex items-center justify-between">
                  <h1 className="text-2xl font-semibold">Your Classes</h1>
                  <Button variant="outline" size="sm">
                    <PlusIcon className="h-4 w-4" />
                    Add New Class
                  </Button>
                </div>
                <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
                  <Card>
                    <CardHeader>
                      <CardTitle>Introduction to Computer Science</CardTitle>
                      <CardDescription>
                        <div className="flex items-center gap-2">
                          <ClockIcon className="h-4 w-4 text-muted-foreground" />
                          <span>9:00 AM - 10:30 AM</span>
                        </div>
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="grid gap-2">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <UsersIcon className="h-4 w-4 text-muted-foreground" />
                          <span>45 students</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <ActivityIcon className="h-4 w-4 text-muted-foreground" />
                          <span>32 present</span>
                        </div>
                      </div>
                    </CardContent>
                    <CardFooter>
                      <Button
                        variant="outline"
                        size="sm"
                        className="w-full"
                        onClick={() => console.log("Clicked on class card")}
                      >
                        View Class
                      </Button>
                    </CardFooter>
                  </Card>
                  <Card>
                    <CardHeader>
                      <CardTitle>Calculus I</CardTitle>
                      <CardDescription>
                        <div className="flex items-center gap-2">
                          <ClockIcon className="h-4 w-4 text-muted-foreground" />
                          <span>11:00 AM - 12:30 PM</span>
                        </div>
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="grid gap-2">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <UsersIcon className="h-4 w-4 text-muted-foreground" />
                          <span>28 students</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <ActivityIcon className="h-4 w-4 text-muted-foreground" />
                          <span>25 present</span>
                        </div>
                      </div>
                    </CardContent>
                    <CardFooter>
                      <Button
                        variant="outline"
                        size="sm"
                        className="w-full"
                        onClick={() => console.log("Clicked on class card")}
                      >
                        View Class
                      </Button>
                    </CardFooter>
                  </Card>
                  <Card>
                    <CardHeader>
                      <CardTitle>Introduction to Psychology</CardTitle>
                      <CardDescription>
                        <div className="flex items-center gap-2">
                          <ClockIcon className="h-4 w-4 text-muted-foreground" />
                          <span>1:00 PM - 2:30 PM</span>
                        </div>
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="grid gap-2">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <UsersIcon className="h-4 w-4 text-muted-foreground" />
                          <span>35 students</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <ActivityIcon className="h-4 w-4 text-muted-foreground" />
                          <span>30 present</span>
                        </div>
                      </div>
                    </CardContent>
                    <CardFooter>
                      <Button
                        variant="outline"
                        size="sm"
                        className="w-full"
                        onClick={() => console.log("Clicked on class card")}
                      >
                        View Class
                      </Button>
                    </CardFooter>
                  </Card>
                  <Card>
                    <CardHeader>
                      <CardTitle>Introduction to Literature</CardTitle>
                      <CardDescription>
                        <div className="flex items-center gap-2">
                          <ClockIcon className="h-4 w-4 text-muted-foreground" />
                          <span>3:00 PM - 4:30 PM</span>
                        </div>
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="grid gap-2">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <UsersIcon className="h-4 w-4 text-muted-foreground" />
                          <span>25 students</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <ActivityIcon className="h-4 w-4 text-muted-foreground" />
                          <span>22 present</span>
                        </div>
                      </div>
                    </CardContent>
                    <CardFooter>
                      <Button
                        variant="outline"
                        size="sm"
                        className="w-full"
                        onClick={() => console.log("Clicked on class card")}
                      >
                        View Class
                      </Button>
                    </CardFooter>
                  </Card>
                </div>
              </div>
            </TabsContent>
            <TabsContent value="attendance">
              <div className="grid gap-4">
                <div className="flex items-center justify-between">
                  <h2 className="text-xl font-semibold">Introduction to Computer Science</h2>
                  <div className="flex items-center gap-2">
                    <Button variant="outline" size="sm">
                      <UsersIcon className="h-4 w-4" />
                      Manage Students
                    </Button>
                    <Button variant="outline" size="sm">
                      <ActivityIcon className="h-4 w-4" />
                      Take Attendance
                    </Button>
                  </div>
                </div>
                <Card>
                  <CardContent>
                    <div className="grid gap-4">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <ClockIcon className="h-4 w-4 text-muted-foreground" />
                          <span>9:00 AM - 10:30 AM</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <UsersIcon className="h-4 w-4 text-muted-foreground" />
                          <span>45 students</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <ActivityIcon className="h-4 w-4 text-muted-foreground" />
                          <span>32 present</span>
                        </div>
                      </div>
                      <Table>
                        <TableHeader>
                          <TableRow>
                            <TableHead>Name</TableHead>
                            <TableHead>Email</TableHead>
                            <TableHead>Attendance</TableHead>
                          </TableRow>
                        </TableHeader>
                        <TableBody>
                          <TableRow>
                            <TableCell>John Doe</TableCell>
                            <TableCell>john@example.com</TableCell>
                            <TableCell>
                              <Checkbox defaultChecked />
                            </TableCell>
                          </TableRow>
                          <TableRow>
                            <TableCell>Jane Smith</TableCell>
                            <TableCell>jane@example.com</TableCell>
                            <TableCell>
                              <Checkbox defaultChecked />
                            </TableCell>
                          </TableRow>
                          <TableRow>
                            <TableCell>Bob Johnson</TableCell>
                            <TableCell>bob@example.com</TableCell>
                            <TableCell>
                              <Checkbox />
                            </TableCell>
                          </TableRow>
                          <TableRow>
                            <TableCell>Alice Williams</TableCell>
                            <TableCell>alice@example.com</TableCell>
                            <TableCell>
                              <Checkbox defaultChecked />
                            </TableCell>
                          </TableRow>
                          <TableRow>
                            <TableCell>Tom Davis</TableCell>
                            <TableCell>tom@example.com</TableCell>
                            <TableCell>
                              <Checkbox />
                            </TableCell>
                          </TableRow>
                        </TableBody>
                      </Table>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </TabsContent>
            <TabsContent value="grades">
              <div className="grid gap-4">
                <div className="flex items-center justify-between">
                  <h2 className="text-xl font-semibold">Introduction to Computer Science</h2>
                  <div className="flex items-center gap-2">
                    <Button variant="outline" size="sm">
                      <UsersIcon className="h-4 w-4" />
                      Manage Grades
                    </Button>
                    <Button variant="outline" size="sm">
                      <ActivityIcon className="h-4 w-4" />
                      Enter New Grades
                    </Button>
                  </div>
                </div>
                <Card>
                  <CardContent>
                    <div className="grid gap-4">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <ClockIcon className="h-4 w-4 text-muted-foreground" />
                          <span>9:00 AM - 10:30 AM</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <UsersIcon className="h-4 w-4 text-muted-foreground" />
                          <span>45 students</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <ActivityIcon className="h-4 w-4 text-muted-foreground" />
                          <span>32 present</span>
                        </div>
                      </div>
                      <Table>
                        <TableHeader>
                          <TableRow>
                            <TableHead>Name</TableHead>
                            <TableHead>Email</TableHead>
                            <TableHead>Grade</TableHead>
                          </TableRow>
                        </TableHeader>
                        <TableBody>
                          <TableRow>
                            <TableCell>John Doe</TableCell>
                            <TableCell>john@example.com</TableCell>
                            <TableCell>A</TableCell>
                          </TableRow>
                          <TableRow>
                            <TableCell>Jane Smith</TableCell>
                            <TableCell>jane@example.com</TableCell>
                            <TableCell>B+</TableCell>
                          </TableRow>
                          <TableRow>
                            <TableCell>Bob Johnson</TableCell>
                            <TableCell>bob@example.com</TableCell>
                            <TableCell>C</TableCell>
                          </TableRow>
                          <TableRow>
                            <TableCell>Alice Williams</TableCell>
                            <TableCell>alice@example.com</TableCell>
                            <TableCell>A-</TableCell>
                          </TableRow>
                          <TableRow>
                            <TableCell>Tom Davis</TableCell>
                            <TableCell>tom@example.com</TableCell>
                            <TableCell>B</TableCell>
                          </TableRow>
                        </TableBody>
                      </Table>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </main>
    </div>
  )
}

function ActivityIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2" />
    </svg>
  )
}


function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function ClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
