/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/m0Hto6SSkzV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"

export default function notifications() {
  return (
    <div className="flex flex-col w-full min-h-screen">
      
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Upcoming Classes</CardTitle>
              <CalendarIcon className="w-4 h-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="grid gap-2">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Introduction to Programming</div>
                    <div className="text-xs text-muted-foreground">9:00 AM - 10:30 AM</div>
                  </div>
                  <Badge variant="secondary" className="text-xs">
                    New
                  </Badge>
                </div>
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Data Structures and Algorithms</div>
                    <div className="text-xs text-muted-foreground">2:00 PM - 3:30 PM</div>
                  </div>
                  <Badge variant="secondary" className="text-xs">
                    New
                  </Badge>
                </div>
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Web Development Fundamentals</div>
                    <div className="text-xs text-muted-foreground">6:00 PM - 7:30 PM</div>
                  </div>
                  <Badge variant="secondary" className="text-xs">
                    New
                  </Badge>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Attendance Changes</CardTitle>
              <UsersIcon className="w-4 h-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="grid gap-2">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">John Doe</div>
                    <div className="text-xs text-muted-foreground">Introduction to Programming</div>
                  </div>
                  <Badge variant="outline" className="text-xs">
                    Absent
                  </Badge>
                </div>
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Jane Smith</div>
                    <div className="text-xs text-muted-foreground">Data Structures and Algorithms</div>
                  </div>
                  <Badge variant="outline" className="text-xs">
                    Late
                  </Badge>
                </div>
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Michael Johnson</div>
                    <div className="text-xs text-muted-foreground">Web Development Fundamentals</div>
                  </div>
                  <Badge variant="outline" className="text-xs">
                    Excused
                  </Badge>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Administrative Announcements</CardTitle>
              <MegaphoneIcon className="w-4 h-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="grid gap-2">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Campus Closure</div>
                    <div className="text-xs text-muted-foreground">
                      Due to inclement weather, the campus will be closed tomorrow.
                    </div>
                  </div>
                  <Badge variant="secondary" className="text-xs">
                    New
                  </Badge>
                </div>
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Tuition Deadline</div>
                    <div className="text-xs text-muted-foreground">
                      The tuition payment deadline has been extended to the end of the month.
                    </div>
                  </div>
                  <Badge variant="secondary" className="text-xs">
                    New
                  </Badge>
                </div>
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Graduation Ceremony</div>
                    <div className="text-xs text-muted-foreground">
                      The graduation ceremony will be held on June 15th at 2:00 PM.
                    </div>
                  </div>
                  <Badge variant="secondary" className="text-xs">
                    New
                  </Badge>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
        <div>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">All Notifications</CardTitle>
              <Button variant="outline" size="sm">
                Mark All as Read
              </Button>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Type</TableHead>
                    <TableHead>Title</TableHead>
                    <TableHead>Description</TableHead>
                    <TableHead>Time</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>Class</TableCell>
                    <TableCell className="font-medium">Introduction to Programming</TableCell>
                    <TableCell>Your Introduction to Programming class has been moved to 9:00 AM - 10:30 AM.</TableCell>
                    <TableCell>
                      <time dateTime="2023-09-29T09:00:00">9:00 AM</time>
                    </TableCell>
                    <TableCell>
                      <Badge variant="secondary" className="text-xs">
                        New
                      </Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Attendance</TableCell>
                    <TableCell className="font-medium">John Doe</TableCell>
                    <TableCell>John Doe has been marked as absent for the Introduction to Programming class.</TableCell>
                    <TableCell>
                      <time dateTime="2023-09-29T09:15:00">9:15 AM</time>
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline" className="text-xs">
                        Unread
                      </Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Announcement</TableCell>
                    <TableCell className="font-medium">Campus Closure</TableCell>
                    <TableCell>Due to inclement weather, the campus will be closed tomorrow.</TableCell>
                    <TableCell>
                      <time dateTime="2023-09-29T10:00:00">10:00 AM</time>
                    </TableCell>
                    <TableCell>
                      <Badge variant="secondary" className="text-xs">
                        New
                      </Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Class</TableCell>
                    <TableCell className="font-medium">Data Structures and Algorithms</TableCell>
                    <TableCell>
                      Your Data Structures and Algorithms class has been moved to 2:00 PM - 3:30 PM.
                    </TableCell>
                    <TableCell>
                      <time dateTime="2023-09-29T13:00:00">1:00 PM</time>
                    </TableCell>
                    <TableCell>
                      <Badge variant="secondary" className="text-xs">
                        New
                      </Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Attendance</TableCell>
                    <TableCell className="font-medium">Jane Smith</TableCell>
                    <TableCell>
                      Jane Smith has been marked as late for the Data Structures and Algorithms class.
                    </TableCell>
                    <TableCell>
                      <time dateTime="2023-09-29T14:15:00">2:15 PM</time>
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline" className="text-xs">
                        Unread
                      </Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Announcement</TableCell>
                    <TableCell className="font-medium">Tuition Deadline</TableCell>
                    <TableCell>The tuition payment deadline has been extended to the end of the month.</TableCell>
                    <TableCell>
                      <time dateTime="2023-09-29T15:00:00">3:00 PM</time>
                    </TableCell>
                    <TableCell>
                      <Badge variant="secondary" className="text-xs">
                        New
                      </Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Class</TableCell>
                    <TableCell className="font-medium">Web Development Fundamentals</TableCell>
                    <TableCell>Your Web Development Fundamentals class has been moved to 6:00 PM - 7:30 PM.</TableCell>
                    <TableCell>
                      <time dateTime="2023-09-29T17:00:00">5:00 PM</time>
                    </TableCell>
                    <TableCell>
                      <Badge variant="secondary" className="text-xs">
                        New
                      </Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Attendance</TableCell>
                    <TableCell className="font-medium">Michael Johnson</TableCell>
                    <TableCell>
                      Michael Johnson has been marked as excused for the Web Development Fundamentals class.
                    </TableCell>
                    <TableCell>
                      <time dateTime="2023-09-29T18:15:00">6:15 PM</time>
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline" className="text-xs">
                        Unread
                      </Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Announcement</TableCell>
                    <TableCell className="font-medium">Graduation Ceremony</TableCell>
                    <TableCell>The graduation ceremony will be held on June 15th at 2:00 PM.</TableCell>
                    <TableCell>
                      <time dateTime="2023-09-29T18:30:00">6:30 PM</time>
                    </TableCell>
                    <TableCell>
                      <Badge variant="secondary" className="text-xs">
                        New
                      </Badge>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}

function BellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}


function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function MegaphoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 11 18-5v12L3 14v-3z" />
      <path d="M11.6 16.8a3 3 0 1 1-5.8-1.6" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
