/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5xAWVl95u8a
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbSeparator, BreadcrumbPage } from "@/components/ui/breadcrumb"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuCheckboxItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Calendar } from "@/components/ui/calendar"
import { Progress } from "@/components/ui/progress"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"

export default function scheduler() {
  return (
    <div className="flex min-h-screen w-full flex-col bg-background">
      <header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b bg-background px-6">
        <div className="flex items-center gap-4">
          <Link href="#" className="flex items-center gap-2 text-lg font-semibold" prefetch={false}>
            <CalendarIcon className="h-6 w-6" />
            <span className="sr-only">Faculty Scheduler</span>
          </Link>
          <Breadcrumb className="hidden md:flex">
            <BreadcrumbList>
              <BreadcrumbItem>
                <BreadcrumbLink asChild>
                  <Link href="#" prefetch={false}>
                    Dashboard
                  </Link>
                </BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator />
              <BreadcrumbItem>
                <BreadcrumbPage>Schedule</BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>
        </div>
        <div className="flex items-center gap-4">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" size="icon" className="overflow-hidden rounded-full">
                <img
                  src="/placeholder.svg"
                  width={36}
                  height={36}
                  alt="Avatar"
                  className="overflow-hidden rounded-full"
                  style={{ aspectRatio: "36/36", objectFit: "cover" }}
                />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>John Doe</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Notifications</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex flex-1 flex-col gap-6 p-6 sm:p-10">
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          <Card>
            <CardHeader>
              <CardTitle>Upcoming Classes</CardTitle>
              <CardDescription>View and manage your class schedule.</CardDescription>
            </CardHeader>
            <CardContent>
              <Calendar mode="month" className="rounded-lg border bg-background p-4" />
            </CardContent>
            <CardFooter>
              <Button>Manage Schedule</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Room Availability</CardTitle>
              <CardDescription>Check and assign rooms for your classes.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 gap-4">
                <div className="flex flex-col items-center gap-2">
                  <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground">
                    <BuildingIcon className="h-6 w-6" />
                  </div>
                  <div className="text-sm font-medium">Main Building</div>
                  <div className="text-xs text-muted-foreground">10 available rooms</div>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <div className="flex h-12 w-12 items-center justify-center rounded-full bg-accent text-accent-foreground">
                    <BuildingIcon className="h-6 w-6" />
                  </div>
                  <div className="text-sm font-medium">Science Building</div>
                  <div className="text-xs text-muted-foreground">5 available rooms</div>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <div className="flex h-12 w-12 items-center justify-center rounded-full bg-secondary text-secondary-foreground">
                    <BuildingIcon className="h-6 w-6" />
                  </div>
                  <div className="text-sm font-medium">Arts Building</div>
                  <div className="text-xs text-muted-foreground">8 available rooms</div>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <div className="flex h-12 w-12 items-center justify-center rounded-full bg-muted text-muted-foreground">
                    <BuildingIcon className="h-6 w-6" />
                  </div>
                  <div className="text-sm font-medium">Library</div>
                  <div className="text-xs text-muted-foreground">3 available rooms</div>
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button>Manage Rooms</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Semester Plan</CardTitle>
              <CardDescription>View and configure your semester schedule.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="flex items-center justify-between">
                  <div className="text-sm font-medium">Fall 2023</div>
                  <div className="text-xs text-muted-foreground">Aug 28 - Dec 15</div>
                </div>
                <Progress value={75} aria-label="75% complete" />
                <div className="flex items-center justify-between">
                  <div className="text-sm font-medium">Spring 2024</div>
                  <div className="text-xs text-muted-foreground">Jan 8 - May 10</div>
                </div>
                <Progress value={25} aria-label="25% complete" />
              </div>
            </CardContent>
            <CardFooter>
              <Button>Manage Semesters</Button>
            </CardFooter>
          </Card>
        </div>
        <Card>
          <CardHeader>
            <CardTitle>Class Schedule</CardTitle>
            <CardDescription>View and manage your class schedule for the current semester.</CardDescription>
          </CardHeader>
          <CardContent>
            <Tabs defaultValue="week">
              <TabsList>
                <TabsTrigger value="week">Week</TabsTrigger>
                <TabsTrigger value="month">Month</TabsTrigger>
              </TabsList>
              <TabsContent value="week">
                <div className="grid grid-cols-[200px_1fr] gap-4">
                  <div className="flex flex-col gap-4">
                    <div className="grid gap-2">
                      <div className="flex items-center justify-between">
                        <div className="text-sm font-medium">Monday</div>
                        <div className="text-xs text-muted-foreground">Aug 28 - Dec 15</div>
                      </div>
                      <div className="grid gap-1">
                        <div className="flex items-center gap-2 rounded-md bg-accent p-2 text-accent-foreground">
                          <ClockIcon className="h-4 w-4" />
                          <div className="text-sm font-medium">9:00 AM - 10:30 AM</div>
                          <div className="ml-auto text-xs">Intro to Computer Science</div>
                        </div>
                        <div className="flex items-center gap-2 rounded-md bg-secondary p-2 text-secondary-foreground">
                          <ClockIcon className="h-4 w-4" />
                          <div className="text-sm font-medium">11:00 AM - 12:30 PM</div>
                          <div className="ml-auto text-xs">Calculus I</div>
                        </div>
                      </div>
                    </div>
                    <div className="grid gap-2">
                      <div className="flex items-center justify-between">
                        <div className="text-sm font-medium">Tuesday</div>
                        <div className="text-xs text-muted-foreground">Aug 28 - Dec 15</div>
                      </div>
                      <div className="grid gap-1">
                        <div className="flex items-center gap-2 rounded-md bg-primary p-2 text-primary-foreground">
                          <ClockIcon className="h-4 w-4" />
                          <div className="text-sm font-medium">9:00 AM - 10:30 AM</div>
                          <div className="ml-auto text-xs">Intro to Programming</div>
                        </div>
                        <div className="flex items-center gap-2 rounded-md bg-muted p-2 text-muted-foreground">
                          <ClockIcon className="h-4 w-4" />
                          <div className="text-sm font-medium">11:00 AM - 12:30 PM</div>
                          <div className="ml-auto text-xs">Physics I</div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="grid gap-4">
                    <div className="flex items-center justify-between">
                      <div className="text-sm font-medium">Upcoming Classes</div>
                      <div className="flex items-center gap-2">
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button variant="outline" size="sm" className="h-7 gap-1 text-sm">
                              <FilterIcon className="h-4 w-4" />
                              <span className="sr-only sm:not-sr-only">Filter</span>
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="end">
                            <DropdownMenuLabel>Filter by</DropdownMenuLabel>
                            <DropdownMenuSeparator />
                            <DropdownMenuCheckboxItem checked>Instructor</DropdownMenuCheckboxItem>
                            <DropdownMenuCheckboxItem>Room</DropdownMenuCheckboxItem>
                            <DropdownMenuCheckboxItem>Time</DropdownMenuCheckboxItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                        <Button size="sm" variant="outline" className="h-7 gap-1 text-sm">
                          <ImportIcon className="h-4 w-4" />
                          <span className="sr-only sm:not-sr-only">Export</span>
                        </Button>
                      </div>
                    </div>
                    <Table>
                      <TableHeader>
                        <TableRow>
                          <TableHead>Time</TableHead>
                          <TableHead>Course</TableHead>
                          <TableHead>Instructor</TableHead>
                          <TableHead>Room</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        <TableRow>
                          <TableCell>
                            <div className="text-sm font-medium">9:00 AM - 10:30 AM</div>
                            <div className="text-xs text-muted-foreground">Monday</div>
                          </TableCell>
                          <TableCell>
                            <div className="text-sm font-medium">Intro to Computer Science</div>
                            <div className="text-xs text-muted-foreground">CS101</div>
                          </TableCell>
                          <TableCell>
                            <div className="text-sm font-medium">Dr. Jane Smith</div>
                            <div className="text-xs text-muted-foreground">Computer Science Department</div>
                          </TableCell>
                          <TableCell>
                            <div className="text-sm font-medium">Room 101</div>
                            <div className="text-xs text-muted-foreground">Main Building</div>
                          </TableCell>
                        </TableRow>
                        <TableRow>
                          <TableCell>
                            <div className="text-sm font-medium">11:00 AM - 12:30 PM</div>
                            <div className="text-xs text-muted-foreground">Monday</div>
                          </TableCell>
                          <TableCell>
                            <div className="text-sm font-medium">Calculus I</div>
                            <div className="text-xs text-muted-foreground">MATH101</div>
                          </TableCell>
                          <TableCell>
                            <div className="text-sm font-medium">Dr. John Doe</div>
                            <div className="text-xs text-muted-foreground">Mathematics Department</div>
                          </TableCell>
                          <TableCell>
                            <div className="text-sm font-medium">Room 201</div>
                            <div className="text-xs text-muted-foreground">Science Building</div>
                          </TableCell>
                        </TableRow>
                        <TableRow>
                          <TableCell>
                            <div className="text-sm font-medium">9:00 AM - 10:30 AM</div>
                            <div className="text-xs text-muted-foreground">Tuesday</div>
                          </TableCell>
                          <TableCell>
                            <div className="text-sm font-medium">Intro to Programming</div>
                            <div className="text-xs text-muted-foreground">CS102</div>
                          </TableCell>
                          <TableCell>
                            <div className="text-sm font-medium">Dr. Sarah Lee</div>
                            <div className="text-xs text-muted-foreground">Computer Science Department</div>
                          </TableCell>
                          <TableCell>
                            <div className="text-sm font-medium">Room 301</div>
                            <div className="text-xs text-muted-foreground">Main Building</div>
                          </TableCell>
                        </TableRow>
                        <TableRow>
                          <TableCell>
                            <div className="text-sm font-medium">11:00 AM - 12:30 PM</div>
                            <div className="text-xs text-muted-foreground">Tuesday</div>
                          </TableCell>
                          <TableCell>
                            <div className="text-sm font-medium">Physics I</div>
                            <div className="text-xs text-muted-foreground">PHYS101</div>
                          </TableCell>
                          <TableCell>
                            <div className="text-sm font-medium">Dr. Michael Brown</div>
                            <div className="text-xs text-muted-foreground">Physics Department</div>
                          </TableCell>
                          <TableCell>
                            <div className="text-sm font-medium">Room 401</div>
                            <div className="text-xs text-muted-foreground">Science Building</div>
                          </TableCell>
                        </TableRow>
                      </TableBody>
                    </Table>
                  </div>
                </div>
              </TabsContent>
            </Tabs>
          </CardContent>
        </Card>
      </main>
    </div>
  )
}

function BuildingIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="20" x="4" y="2" rx="2" ry="2" />
      <path d="M9 22v-4h6v4" />
      <path d="M8 6h.01" />
      <path d="M16 6h.01" />
      <path d="M12 6h.01" />
      <path d="M12 10h.01" />
      <path d="M12 14h.01" />
      <path d="M16 10h.01" />
      <path d="M16 14h.01" />
      <path d="M8 10h.01" />
      <path d="M8 14h.01" />
    </svg>
  )
}


function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function ClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}


function ImportIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3v12" />
      <path d="m8 11 4 4 4-4" />
      <path d="M8 5H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-4" />
    </svg>
  )
}
