/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/90SODyyTj9C
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export default function signin() {
  return (
    <div className="mx-auto max-w-sm space-y-6 h-[500px] mt-24">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Sign In</h1>
        <p className="text-muted-foreground">Enter your email and password to access your account.</p>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input id="email" type="email" placeholder="m@example.com" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="password">Password</Label>
          <Input id="password" type="password" required />
        </div>
        <Button type="submit" className="w-full">
          Sign In
        </Button>
        <Link href="/signup" className="inline-block w-full text-center text-sm underline" prefetch={false}>
          Don't have an account
        </Link>
        <Link href="reset-password" className="inline-block w-full text-center text-sm underline" prefetch={false}>
          Forgot your password?
        </Link>
      </div>
    </div>
  )
}
