/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/W62uUW8qYt3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Collapsible, CollapsibleItem, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"

export default function support() {
  return (
    <div className="w-full max-w-6xl mx-auto py-12 md:py-20">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
        <div>
          <h2 className="text-3xl font-bold mb-6">Get in Touch</h2>
          <Card>
            <CardContent>
              <form className="grid gap-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="grid gap-2">
                    <Label htmlFor="name">Name</Label>
                    <Input id="name" placeholder="Enter your name" />
                  </div>
                  <div className="grid gap-2">
                    <Label htmlFor="email">Email</Label>
                    <Input id="email" type="email" placeholder="Enter your email" />
                  </div>
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="subject">Subject</Label>
                  <Input id="subject" placeholder="Briefly describe your issue" />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="message">Message</Label>
                  <Textarea id="message" placeholder="Provide more details" className="min-h-[150px]" />
                </div>
                <Button type="submit" className="w-full">
                  Submit
                </Button>
              </form>
            </CardContent>
          </Card>
        </div>
        <div>
          <h2 className="text-3xl font-bold mb-6">Frequently Asked Questions</h2>
          <Card>
            <CardContent>
              <Collapsible className="space-y-4">
                <div>
                  <CollapsibleTrigger className="flex items-center justify-between w-full">
                    <h3 className="text-lg font-medium">How do I update my billing information?</h3>
                    <ChevronDownIcon className="h-5 w-5 transition-transform duration-300 [&[data-state=open]]:rotate-180" />
                  </CollapsibleTrigger>
                  <CollapsibleContent>
                    <p className="text-muted-foreground">
                      To update your billing information, log into your account and navigate to the Billing section.
                      There you can update your payment method, address, and other relevant details.
                    </p>
                  </CollapsibleContent>
                </div>
                <div>
                  <CollapsibleTrigger className="flex items-center justify-between w-full">
                    <h3 className="text-lg font-medium">What is your refund policy?</h3>
                    <ChevronDownIcon className="h-5 w-5 transition-transform duration-300 [&[data-state=open]]:rotate-180" />
                  </CollapsibleTrigger>
                  <CollapsibleContent>
                    <p className="text-muted-foreground">
                      We offer a 30-day money-back guarantee on all our products. If you're not satisfied with your
                      purchase, you can request a full refund within 30 days of your order.
                    </p>
                  </CollapsibleContent>
                </div>
                <div>
                  <CollapsibleTrigger className="flex items-center justify-between w-full">
                    <h3 className="text-lg font-medium">How do I cancel my subscription?</h3>
                    <ChevronDownIcon className="h-5 w-5 transition-transform duration-300 [&[data-state=open]]:rotate-180" />
                  </CollapsibleTrigger>
                  <CollapsibleContent>
                    <p className="text-muted-foreground">
                      To cancel your subscription, log into your account and navigate to the Billing section. There you
                      can cancel your active subscription. If you have any issues, please contact our support team.
                    </p>
                  </CollapsibleContent>
                </div>
              </Collapsible>
            </CardContent>
          </Card>
        </div>
      </div>
      <div className="mt-12 md:mt-20">
        <h2 className="text-3xl font-bold mb-6">Live Chat</h2>
        <Card>
          <CardContent>
            <div className="flex flex-col h-[400px]">
              <div className="flex-1 overflow-y-auto p-4 space-y-4">
                <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm ml-auto bg-primary text-primary-foreground">
                  Hi, how can I assist you today?
                </div>
                <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-muted">
                  I'm having trouble with my account. Can you help me?
                </div>
                <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm ml-auto bg-primary text-primary-foreground">
                  Absolutely, let me take a look. What's the issue you're experiencing?
                </div>
              </div>
              <div className="border-t px-4 py-3">
                <form className="flex items-center w-full space-x-2">
                  <Input id="message" placeholder="Type your message..." className="flex-1" autoComplete="off" />
                  <Button type="submit" size="icon">
                    <SendIcon className="w-4 h-4" />
                    <span className="sr-only">Send</span>
                  </Button>
                </form>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
