/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/aghgkrLMHWd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export default function testimonials() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 px-12 md:mx-24 lg:mx-32 xl:mx-48 ">
      <div className="container grid items-center justify-center gap-10 px-4 text-center md:px-6 lg:gap-16">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">What Our Community Says</h2>
          <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Hear from the people who matter most - our faculty and students.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          <Card className="p-6 space-y-4">
            <div className="flex items-center gap-4">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div>
                <h4 className="text-lg font-semibold">John Doe</h4>
                <p className="text-sm text-muted-foreground">Professor of Computer Science</p>
              </div>
            </div>
            <blockquote className="text-muted-foreground">
              "The program has been a game-changer for our students. The hands-on approach and industry-relevant
              curriculum have prepared them for success in their careers."
            </blockquote>
          </Card>
          <Card className="p-6 space-y-4">
            <div className="flex items-center gap-4">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>JS</AvatarFallback>
              </Avatar>
              <div>
                <h4 className="text-lg font-semibold">Jane Smith</h4>
                <p className="text-sm text-muted-foreground">Senior Computer Science Student</p>
              </div>
            </div>
            <blockquote className="text-muted-foreground">
              "The program has been an incredible experience. The faculty are knowledgeable and passionate, and the
              opportunities for hands-on learning have been invaluable."
            </blockquote>
          </Card>
          <Card className="p-6 space-y-4">
            <div className="flex items-center gap-4">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>MR</AvatarFallback>
              </Avatar>
              <div>
                <h4 className="text-lg font-semibold">Michael Rodriguez</h4>
                <p className="text-sm text-muted-foreground">Assistant Professor of Computer Science</p>
              </div>
            </div>
            <blockquote className="text-muted-foreground">
              "The curriculum is truly cutting-edge, and the focus on practical skills has been invaluable for our
              students. I'm proud to be a part of this program."
            </blockquote>
          </Card>
          <Card className="p-6 space-y-4">
            <div className="flex items-center gap-4">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>ES</AvatarFallback>
              </Avatar>
              <div>
                <h4 className="text-lg font-semibold">Emily Simmons</h4>
                <p className="text-sm text-muted-foreground">Junior Computer Science Student</p>
              </div>
            </div>
            <blockquote className="text-muted-foreground">
              "The program has exceeded my expectations. The faculty are incredibly supportive, and the opportunities
              for networking and internships have been game-changing."
            </blockquote>
          </Card>
        </div>
      </div>
    </section>
  )
}
