/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/bsojsDEGtvX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"

export default function workflow() {
  const [activeTab, setActiveTab] = useState("faculty-login")
  return (
    <div className="w-full max-w-4xl mx-auto">
       <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl py-12">How it works</h2>
      <Tabs defaultValue="faculty-login" className="border-b" value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="flex space-x-6">
          <TabsTrigger value="faculty-login">Faculty Login</TabsTrigger>
          <TabsTrigger value="course-management">Course Management</TabsTrigger>
          <TabsTrigger value="student-enrollment">Student Enrollment</TabsTrigger>
          <TabsTrigger value="learning-materials">Learning Materials</TabsTrigger>
          <TabsTrigger value="assignment-submission">Assignment Submission</TabsTrigger>
          <TabsTrigger value="grading-feedback">Grading and Feedback</TabsTrigger>
          <TabsTrigger value="communication">Communication</TabsTrigger>
          <TabsTrigger value="progress-tracking">Progress Tracking</TabsTrigger>
        </TabsList>
        <TabsContent value="faculty-login">
          <Card>
            <CardHeader>
              <CardTitle>Faculty Login</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-4">
                <UserIcon className="h-8 w-8" />
                <p>Faculty members can log in to the app using their credentials.</p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="course-management">
          <Card>
            <CardHeader>
              <CardTitle>Course Management</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-start gap-4">
                <BookIcon className="h-8 w-8" />
                <div>
                  <p>Faculty can create and manage their courses, including:</p>
                  <ul className="mt-2 list-disc pl-4 text-muted-foreground">
                    <li>Adding course materials</li>
                    <li>Assigning tasks and assignments</li>
                    <li>Posting announcements</li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="student-enrollment">
          <Card>
            <CardHeader>
              <CardTitle>Student Enrollment</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-4">
                <UsersIcon className="h-8 w-8" />
                <p>Students can enroll in courses offered by faculty.</p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="learning-materials">
          <Card>
            <CardHeader>
              <CardTitle>Learning Materials</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-start gap-4">
                <FileTextIcon className="h-8 w-8" />
                <div>
                  <p>Students can access course materials, such as:</p>
                  <ul className="mt-2 list-disc pl-4 text-muted-foreground">
                    <li>Lecture slides</li>
                    <li>Readings</li>
                    <li>Videos</li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="assignment-submission">
          <Card>
            <CardHeader>
              <CardTitle>Assignment Submission</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-4">
                <UploadIcon className="h-8 w-8" />
                <p>Students can submit assignments and projects through the app.</p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="grading-feedback">
          <Card>
            <CardHeader>
              <CardTitle>Grading and Feedback</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-start gap-4">
                <FilePenIcon className="h-8 w-8" />
                <div>
                  <p>Faculty can:</p>
                  <ul className="mt-2 list-disc pl-4 text-muted-foreground">
                    <li>Grade student work</li>
                    <li>Provide feedback within the app</li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="communication">
          <Card>
            <CardHeader>
              <CardTitle>Communication</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-start gap-4">
                <MessageCircleIcon className="h-8 w-8" />
                <div>
                  <p>Faculty and students can communicate through the app, using features like:</p>
                  <ul className="mt-2 list-disc pl-4 text-muted-foreground">
                    <li>Discussion forums</li>
                    <li>Chat</li>
                    <li>Announcements</li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="progress-tracking">
          <Card>
            <CardHeader>
              <CardTitle>Progress Tracking</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-4">
                <BarChartIcon className="h-8 w-8" />
                <p>Students can track their progress and performance in the courses they are enrolled in.</p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}

function BarChartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  )
}


function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function FilePenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>
  )
}


function FileTextIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10 9H8" />
      <path d="M16 13H8" />
      <path d="M16 17H8" />
    </svg>
  )
}


function MessageCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>
  )
}


function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
